### ISSUE TITLE
extract-text-webpack-plugin loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [ng-seed/angular-webpack-config#29]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

I am getting the below error when running spa-prod build. Based on https://github.com/angular/angular-cli/issues/5628 it seems to be related to the configuration. 

Error: Child compilation failed:
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (C:\Users\jirka\OneDrive\Development\Templates\Angular\Angular\Web\Angular.Web\node_modules\extract-text-webpack-plugin\loader.js:27:9):
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

**Expected/desired behavior**

 Should be no error. 

**Minimal reproduction of the problem with instructions**

Run spa-prod build with node modules. I haven't been able to identify which node module causes the issue.

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** X.Y.Z

Issue in angular 4.3.4

* **Browser:**
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

* **For Tooling issues:**
- Node version: XX  
- Platform:  

* Others:

**Comment by PTC-JoshuaMatthews** [comment]
I am able to work around it by manually editing the config. See below. Maybe these edits can become standard?

const bundle = {
    spa: {
        dev: function(done) {
            const conf = $.webpackConfig({ env: 'dev' }, $$.root, settings);

            $.webpack(conf)
                .run(function(err, stats) {
                    $$.webpackFormatter(err, stats, done);
                });
        },
        prod: function(done) {
            const conf = $.webpackConfig({ env: 'prod' }, $$.root, settings);

        
            //This adds a raw-loader rule for node modules folder, which is the path at include[1]
            conf.module.rules.push({
                test: /\.scss$/,
                include: conf.module.rules[3].include[1],
                use: ['raw-loader', 'sass-loader']
            });

            //This removes include[1] node modules folder from the exising scss rule so it still applies ExtractTextPlugin for app styles
            conf.module.rules[3].include.splice(conf.module.rules[3].include.indexOf(conf.module.rules[3].include[1]), 1);

            //Uncomment these to see config in log
            //console.log(conf);
            //console.log(JSON.stringify(conf.module.rules));

            $.webpack(conf)
                .run(function(err, stats) {
                    $$.webpackFormatter(err, stats, done);
                });
        }
    },

**Comment by fulls1z3** [comment]
@PTC-JoshuaMatthews I'll have a look on it when I have time available, and I really appreciate your help by coming up with a working solution.

Meanwhile, would you consider creating a fork and make changes and send a Pull Request? This way, things can be accelerated and I'll be able to deploy a new version just after all automated tests pass.

**Comment by fulls1z3** [comment]
@PTC-JoshuaMatthews I digged into it a little, so basically your solution suggests to remove to *SCSS* in `node_modules` from the external bundle and process it within the app styles? Is this information correct? If so, I'll come up with something useful.

**Comment by PTC-JoshuaMatthews** [comment]
Ultimately we need node modules not to use the ExtractTextPlugin, so directing all app styles to the plugin, and all other styles to sass-loader/raw-loader

`{
                test: /\.scss$/,
                include: helpers.root('app/styles'),
                use: extractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: ['css-loader', 'sass-loader']
                })
            },
            {
                test: /\.scss$/,
                exclude: helpers.root('app/styles'),
                use: ['raw-loader', 'sass-loader']
            }`
