### ISSUE TITLE
ability to deploy assets to custom domain

### ISSUE THREAD

**Issue by vlados** [ng-seed/angular-webpack-config#35]
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```
What you think about setting in the configuration option to build production files with custom domain for assets. This is good because right now everything goes thru nodejs (express).
This is very good for production

**Comment by fulls1z3** [comment]
@vlados sounds useful actually, could you please elaborate more details?
