### ISSUE TITLE
prod devtool is disabled

### ISSUE THREAD

**Issue by vlados** [ng-seed/angular-webpack-config#41]
Why this line is commented? Why not using the config file? 
https://github.com/ng-seed/angular-webpack-config/blob/b1b74e29cd836f45cf4cf8a6d0c70230c0933b04/src/webpack.common.prod.js#L24

**Comment by fulls1z3** [comment]
@vlados did you have an opportunity to compare bundle sizes in both scenarios with this line commented and not, my friend?
