### ISSUE TITLE
[bug] image paths not correct on server side render of HTML

### ISSUE THREAD

**Issue by ChrisDalley** [ng-seed/angular-webpack-config#7]
Hi Burak, 
I might be mistaken on this but currently I have an issue where the initial server render HTML still contains the relative paths to assets rather than the Webpack hashed version causing images not to render until client side has loaded. 
Server side
`<img _ngcontent-c1="" class="logo-image" src="./../../../assets/images/logo/LogoWhite.png"/>`
Client side
`<img _ngcontent-c1="" class="logo-image" src="assets/assets/LogoWhite.42920e8170b8ab35eaf616276ba2dcba.png">`

Previously I worked around this by adding the following test to both the server/node webpack config as well as the browser webpack config where it currently sits in webpack.common.js instead of using the raw-loader.

```
 {
          test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
          use: 'file-loader?name=assets/[name].[hash].[ext]'
}
```

However since extracting the webpack config into its own npm package, this no longer works and trying to merge this test rule in using webpack-merge causes duplication of files with different Hashes. 

Is this similar behaviour that you get when adding images inline in HTML or am I missing something else? 

Thanks,
Chris

**Comment by zagushka** [comment]
I have the same issue,
So far it seems like angular-webpack-config module have relative path at 
node_modules/angular-webpack-config/src/webpack.common.js:40
Changing publicPath: 'assets/' to '/assets/' should fix the issue.

**Comment by fulls1z3** [comment]
@ChrisDalley @zagushka I've checked the issue #8 as well as this one. I've previously set the `publicPath` as relative due to compability with `HMR`. However, I'll investigate this and try to come up with a solution which works for everyone.

Meanwhile @ChrisDalley you can customize the webpack configuration using the `./config/webpack.config.js`. Please look at https://github.com/ng-seed/universal/issues/50#issuecomment-319917262 as an example.

**Comment by insanehong** [comment]
@fulls1z3 
It would be better to separate the image and the font file for override loader.

as is:
```
{
          test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
          use: 'file-loader?name=assets/[name].[hash].[ext]'
}
```

to be: 
```
{
          test: /\.(png|jpe?g|gif)$/,
           use: [
            {
              loader: 'file-loader',
              options: {
                name: 'assets/[name].[ext]'
              }
            }
},
{
          test: /\.(|svg|woff|woff2|ttf|eot|ico)$
          use: [
            {
              loader: 'file-loader',
              options: {
                name: 'assets/[name].[ext]'
              }
            }
},


```
